swagger:
  enabled: true
server:
  port: 9080
spring:
  datasource:
    url: jdbc:mysql://mysql1.dev.ceei.com:32121/cp_report?useUnicode=true&useSSL=false&characterEncoding=utf8
    username: root
    password: rootce

# seafile 配置
seafile:
  systemId: 86                #系统标识
  #文件服务器地址
  host: http://service-seafile-seafile-service.apps.okd.ceei.com
  port: 80                  #文件服务器端口号

#文件上传下载
reportfile:
  uploadDir: "E:/test/report/temp/upload/"
  downloadDir: "E:/test/report/temp/download/"

# sms 配置
sms:
  host: http://47.92.156.192  #sms服务器地址
  port: 10500                 #sms服务器端口号

# 单点登录 配置
sso:
  host: http://ce-security-nginx.apps.okd.ceei.com
  port: 80

# 工作流 服务配置
workflow:
  # 测试服务器
  #  host: http://demo-workflow.apps.okd.ceei.com
  #  port: 80

  host: http://192.168.3.205
  port: 8080

# host: http://192.168.3.249
# port: 8080

# 日志
logging:
  path: E:/workspace/documentmanagementserver/cooperation/logs

