server:
  tomcat:
    uri-encoding: UTF-8
    max-threads: 1000
    min-spare-threads: 30
  connection-timeout: 5000ms
  servlet:
    context-path: /cp/report
spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    max-active: 20
    max-idle: 100
    min-idle: 10
    initial-size: 10
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true
#  devtools:
#    restart:
##      enabled: true
##      additional-paths: src/main/java
#      poll-interval: 3000ms
#      quiet-period: 2999ms

#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.ceei.*.entity
  global-config:
    #数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID", ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: UUID
      #      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      #      field-strategy: NOT_NULL
      #驼峰下划线转换
      column-underline: true
      logic-delete-value: -1
      logic-not-delete-value: 0
    banner: false
  #  #原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'


# 单点登录 路径配置
sso:
  verify: /api/auth/jwt/verify                                      # 验证Authorization有效性
  token: /api/auth/jwt/token                                        # 用户登录
  tenants: /api/admin/user/front/tenants                            # 获取租户
  loginUser: /api/admin/user/front/info                             # 获取登录用户的信息
  role: /api/admin/user/front/user/groups                           # 获取租户下的角色
  departTree: /api/admin/user/front/departsTree?isSuperTenant=      # 获取部门树
  departUser: /api/admin/depart/departmentId/user                   # 获取部门下人员

# seafile 配置（固定）
seafile:
  upload: /seafile/uploadFile           #上传文件路径
  query: /seafile/querySeafileList      #查询文件路径
  attaDomain: attaDomain                #文件批号
  domainId: domainId                    #文件id
  commTreeId: commTreeId                #systemId
  upFile: upFile                        #上传文件参数


# sms 配置（固定）
sms:
  message: /ce-airport/message/sysMessage/add
